=== satyaj/camel-service-demo/src/main/resources/META-INF/Employee.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.example.org/Employee" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="tns">
<element name="Employees"></element>

    <element name="EmployeeRecord">

    <complexType>
    	<sequence>
    		<element name="EmployeeID" type="int" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="FirstName" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="LastName" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="DateOfBirth" type="date"></element>
    		<element name="DepartmentLevel1" type="int"></element>
    		<element name="FilterKey" minOccurs="1" maxOccurs="1">
    			<simpleType>
    				<restriction base="int"></restriction>
    			</simpleType>
    		</element>
    		<element name="Dummy1" type="string"></element>
    		<element name="Dummy2" type="string"></element>
    		<element name="Dummy3" type="string"></element>
    		<element name="Dummy4" type="string"></element>
    		<element name="Dummy5" type="string"></element>
    		<element name="Dummy6" type="string"></element>
    		<element name="Dummy7" type="string"></element>
    		<element name="Dummy8" type="string"></element>
    		<element name="Dummy9" type="string"></element>
    		<element name="Dummy10" type="string"></element>
    		<element name="Dummy11" type="string"></element>
    		<element name="Dummy12" type="string"></element>
    		<element name="Dummy13" type="string"></element>
    		<element name="Dummy14" type="string"></element>
    	</sequence>
    </complexType>


    
</element>
</schema>

=== satyaj/camel-service-demo/EmployeeRecords.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:Employees>
<tns:EmployeeRecord xmlns:tns="http://www.example.org/Employee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Employee Employee.xsd ">
  <tns:EmployeeID>1</tns:EmployeeID>
  <tns:FirstName>John1</tns:FirstName>
  <tns:LastName>Smith1</tns:LastName>
  <tns:DateOfBirth>1975-01-01</tns:DateOfBirth>
  <tns:DepartmentLevel1>1</tns:DepartmentLevel1>
  <tns:FilterKey>1</tns:FilterKey>
  <tns:Dummy1>tns:Dummy1</tns:Dummy1>
  <tns:Dummy2>tns:Dummy2</tns:Dummy2>
  <tns:Dummy3>tns:Dummy3</tns:Dummy3>
  <tns:Dummy4>tns:Dummy4</tns:Dummy4>
  <tns:Dummy5>tns:Dummy5</tns:Dummy5>
  <tns:Dummy6>tns:Dummy6</tns:Dummy6>
  <tns:Dummy7>tns:Dummy7</tns:Dummy7>
  <tns:Dummy8>tns:Dummy8</tns:Dummy8>
  <tns:Dummy9>tns:Dummy9</tns:Dummy9>
  <tns:Dummy10>tns:Dummy10</tns:Dummy10>
  <tns:Dummy11>tns:Dummy11</tns:Dummy11>
  <tns:Dummy12>tns:Dummy12</tns:Dummy12>
  <tns:Dummy13>tns:Dummy13</tns:Dummy13>
  <tns:Dummy14>tns:Dummy14</tns:Dummy14>
</tns:EmployeeRecord>
<tns:EmployeeRecord xmlns:tns="http://www.example.org/Employee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Employee Employee.xsd ">
  <tns:EmployeeID>2</tns:EmployeeID>
  <tns:FirstName>John2</tns:FirstName>
  <tns:LastName>Smith2</tns:LastName>
  <tns:DateOfBirth>1975-01-02</tns:DateOfBirth>
  <tns:DepartmentLevel1>2</tns:DepartmentLevel1>
  <tns:FilterKey>2</tns:FilterKey>
  <tns:Dummy1>tns:Dummy1</tns:Dummy1>
  <tns:Dummy2>tns:Dummy2</tns:Dummy2>
  <tns:Dummy3>tns:Dummy3</tns:Dummy3>
  <tns:Dummy4>tns:Dummy4</tns:Dummy4>
  <tns:Dummy5>tns:Dummy5</tns:Dummy5>
  <tns:Dummy6>tns:Dummy6</tns:Dummy6>
  <tns:Dummy7>tns:Dummy7</tns:Dummy7>
  <tns:Dummy8>tns:Dummy8</tns:Dummy8>
  <tns:Dummy9>tns:Dummy9</tns:Dummy9>
  <tns:Dummy10>tns:Dummy10</tns:Dummy10>
  <tns:Dummy11>tns:Dummy11</tns:Dummy11>
  <tns:Dummy12>tns:Dummy12</tns:Dummy12>
  <tns:Dummy13>tns:Dummy13</tns:Dummy13>
  <tns:Dummy14>tns:Dummy14</tns:Dummy14>
</tns:EmployeeRecord>
<tns:EmployeeRecord xmlns:tns="http://www.example.org/Employee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Employee Employee.xsd ">
  <tns:EmployeeID>3</tns:EmployeeID>
  <tns:FirstName>John3</tns:FirstName>
  <tns:LastName>Smith3</tns:LastName>
  <tns:DateOfBirth>1975-01-03</tns:DateOfBirth>
  <tns:DepartmentLevel1>3</tns:DepartmentLevel1>
  <tns:FilterKey>3</tns:FilterKey>
  <tns:Dummy1>tns:Dummy1</tns:Dummy1>
  <tns:Dummy2>tns:Dummy2</tns:Dummy2>
  <tns:Dummy3>tns:Dummy3</tns:Dummy3>
  <tns:Dummy4>tns:Dummy4</tns:Dummy4>
  <tns:Dummy5>tns:Dummy5</tns:Dummy5>
  <tns:Dummy6>tns:Dummy6</tns:Dummy6>
  <tns:Dummy7>tns:Dummy7</tns:Dummy7>
  <tns:Dummy8>tns:Dummy8</tns:Dummy8>
  <tns:Dummy9>tns:Dummy9</tns:Dummy9>
  <tns:Dummy10>tns:Dummy10</tns:Dummy10>
  <tns:Dummy11>tns:Dummy11</tns:Dummy11>
  <tns:Dummy12>tns:Dummy12</tns:Dummy12>
  <tns:Dummy13>tns:Dummy13</tns:Dummy13>
  <tns:Dummy14>tns:Dummy14</tns:Dummy14>
</tns:EmployeeRecord>
<tns:EmployeeRecord xmlns:tns="http://www.example.org/Employee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Employee Employee.xsd ">
  <tns:EmployeeID>4</tns:EmployeeID>
  <tns:FirstName>John4</tns:FirstName>
  <tns:LastName>Smith4</tns:LastName>
  <tns:DateOfBirth>1975-01-04</tns:DateOfBirth>
  <tns:DepartmentLevel1>4</tns:DepartmentLevel1>
  <tns:FilterKey>4</tns:FilterKey>
  <tns:Dummy1>tns:Dummy1</tns:Dummy1>
  <tns:Dummy2>tns:Dummy2</tns:Dummy2>
  <tns:Dummy3>tns:Dummy3</tns:Dummy3>
  <tns:Dummy4>tns:Dummy4</tns:Dummy4>
  <tns:Dummy5>tns:Dummy5</tns:Dummy5>
  <tns:Dummy6>tns:Dummy6</tns:Dummy6>
  <tns:Dummy7>tns:Dummy7</tns:Dummy7>
  <tns:Dummy8>tns:Dummy8</tns:Dummy8>
  <tns:Dummy9>tns:Dummy9</tns:Dummy9>
  <tns:Dummy10>tns:Dummy10</tns:Dummy10>
  <tns:Dummy11>tns:Dummy11</tns:Dummy11>
  <tns:Dummy12>tns:Dummy12</tns:Dummy12>
  <tns:Dummy13>tns:Dummy13</tns:Dummy13>
  <tns:Dummy14>tns:Dummy14</tns:Dummy14>
</tns:EmployeeRecord>
<tns:EmployeeRecord xmlns:tns="http://www.example.org/Employee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Employee Employee.xsd ">
  <tns:EmployeeID>5</tns:EmployeeID>
  <tns:FirstName>John5</tns:FirstName>
  <tns:LastName>Smith5</tns:LastName>
  <tns:DateOfBirth>1975-01-05</tns:DateOfBirth>
  <tns:DepartmentLevel1>5</tns:DepartmentLevel1>
  <tns:FilterKey>1</tns:FilterKey>
  <tns:Dummy1>tns:Dummy1</tns:Dummy1>
  <tns:Dummy2>tns:Dummy2</tns:Dummy2>
  <tns:Dummy3>tns:Dummy3</tns:Dummy3>
  <tns:Dummy4>tns:Dummy4</tns:Dummy4>
  <tns:Dummy5>tns:Dummy5</tns:Dummy5>
  <tns:Dummy6>tns:Dummy6</tns:Dummy6>
  <tns:Dummy7>tns:Dummy7</tns:Dummy7>
  <tns:Dummy8>tns:Dummy8</tns:Dummy8>
  <tns:Dummy9>tns:Dummy9</tns:Dummy9>
  <tns:Dummy10>tns:Dummy10</tns:Dummy10>
  <tns:Dummy11>tns:Dummy11</tns:Dummy11>
  <tns:Dummy12>tns:Dummy12</tns:Dummy12>
  <tns:Dummy13>tns:Dummy13</tns:Dummy13>
  <tns:Dummy14>tns:Dummy14</tns:Dummy14>
</tns:EmployeeRecord>
<tns:EmployeeRecord xmlns:tns="http://www.example.org/Employee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Employee Employee.xsd ">
  <tns:EmployeeID>6</tns:EmployeeID>
  <tns:FirstName>John6</tns:FirstName>
  <tns:LastName>Smith6</tns:LastName>
  <tns:DateOfBirth>1975-01-06</tns:DateOfBirth>
  <tns:DepartmentLevel1>6</tns:DepartmentLevel1>
  <tns:FilterKey>2</tns:FilterKey>
  <tns:Dummy1>tns:Dummy1</tns:Dummy1>
  <tns:Dummy2>tns:Dummy2</tns:Dummy2>
  <tns:Dummy3>tns:Dummy3</tns:Dummy3>
  <tns:Dummy4>tns:Dummy4</tns:Dummy4>
  <tns:Dummy5>tns:Dummy5</tns:Dummy5>
  <tns:Dummy6>tns:Dummy6</tns:Dummy6>
  <tns:Dummy7>tns:Dummy7</tns:Dummy7>
  <tns:Dummy8>tns:Dummy8</tns:Dummy8>
  <tns:Dummy9>tns:Dummy9</tns:Dummy9>
  <tns:Dummy10>tns:Dummy10</tns:Dummy10>
  <tns:Dummy11>tns:Dummy11</tns:Dummy11>
  <tns:Dummy12>tns:Dummy12</tns:Dummy12>
  <tns:Dummy13>tns:Dummy13</tns:Dummy13>
  <tns:Dummy14>tns:Dummy14</tns:Dummy14>
</tns:EmployeeRecord>
<tns:EmployeeRecord xmlns:tns="http://www.example.org/Employee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Employee Employee.xsd ">
  <tns:EmployeeID>3</tns:EmployeeID>
  <tns:FirstName>John3</tns:FirstName>
  <tns:LastName>Smith3</tns:LastName>
  <tns:DateOfBirth>1975-01-07</tns:DateOfBirth>
  <tns:DepartmentLevel1>7</tns:DepartmentLevel1>
  <tns:FilterKey>3</tns:FilterKey>
  <tns:Dummy1>tns:Dummy1</tns:Dummy1>
  <tns:Dummy2>tns:Dummy2</tns:Dummy2>
  <tns:Dummy3>tns:Dummy3</tns:Dummy3>
  <tns:Dummy4>tns:Dummy4</tns:Dummy4>
  <tns:Dummy5>tns:Dummy5</tns:Dummy5>
  <tns:Dummy6>tns:Dummy6</tns:Dummy6>
  <tns:Dummy7>tns:Dummy7</tns:Dummy7>
  <tns:Dummy8>tns:Dummy8</tns:Dummy8>
  <tns:Dummy9>tns:Dummy9</tns:Dummy9>
  <tns:Dummy10>tns:Dummy10</tns:Dummy10>
  <tns:Dummy11>tns:Dummy11</tns:Dummy11>
  <tns:Dummy12>tns:Dummy12</tns:Dummy12>
  <tns:Dummy13>tns:Dummy13</tns:Dummy13>
  <tns:Dummy14>tns:Dummy14</tns:Dummy14>
</tns:EmployeeRecord>
<tns:EmployeeRecord xmlns:tns="http://www.example.org/Employee" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/Employee Employee.xsd ">
  <tns:EmployeeID>4</tns:EmployeeID>
  <tns:FirstName>John4</tns:FirstName>
  <tns:LastName>Smith4</tns:LastName>
  <tns:DateOfBirth>1975-01-08</tns:DateOfBirth>
  <tns:DepartmentLevel1>8</tns:DepartmentLevel1>
  <tns:FilterKey>4</tns:FilterKey>
  <tns:Dummy1>tns:Dummy1</tns:Dummy1>
  <tns:Dummy2>tns:Dummy2</tns:Dummy2>
  <tns:Dummy3>tns:Dummy3</tns:Dummy3>
  <tns:Dummy4>tns:Dummy4</tns:Dummy4>
  <tns:Dummy5>tns:Dummy5</tns:Dummy5>
  <tns:Dummy6>tns:Dummy6</tns:Dummy6>
  <tns:Dummy7>tns:Dummy7</tns:Dummy7>
  <tns:Dummy8>tns:Dummy8</tns:Dummy8>
  <tns:Dummy9>tns:Dummy9</tns:Dummy9>
  <tns:Dummy10>tns:Dummy10</tns:Dummy10>
  <tns:Dummy11>tns:Dummy11</tns:Dummy11>
  <tns:Dummy12>tns:Dummy12</tns:Dummy12>
  <tns:Dummy13>tns:Dummy13</tns:Dummy13>
  <tns:Dummy14>tns:Dummy14</tns:Dummy14>
</tns:EmployeeRecord>
</tns:Employees>
